version: '3.1'

services:
    db:
        container_name: pmg_postgress
        image: postgres
        restart: always
        environment:
            - POSTGRES_DB=passmoilgoss
            - POSTGRES_USER=pmg
            - POSTGRES_PASSWORD=pmg
        ports:
            - 5432:5432
